### ISSUE TITLE
Convert .docx files to Markdown

### ISSUE THREAD

**Issue by ExplodingLemur** [phase4ground/documents#12]
.docx files are a friction point for documentation access.  Converting these to Github Markdown will allow users to see them rendered in their browsers immediately without having to download a file and open in a text editor.

**Comment by ExplodingLemur** [comment]
I've got a shell script that uses Pandoc to create Markdown copies of all .docx files in a directory tree, including extracting images and embedding imgrefs and creating proper TOC entries.  There are a few bugs at the moment though (likely regex related).  Once I get that ironed out I'll branch, convert, and merge.

**Comment by Abraxas3d** [comment]
Thank you so much!
