### ISSUE TITLE
Make Teams list as per review 30 July 2020

### ISSUE THREAD

**Issue by Abraxas3d** [phase4ground/documents#14]

**Comment by Abraxas3d** [comment]
Need to figure out a way for people to easily add/leave these team lists.

**Comment by jimt** [comment]
If you want it to be _really_ easy, you might use the GitHub wiki feature.

A pull request for a list in the repository is not much more difficult and allows review.

**Comment by Abraxas3d** [comment]
Wiki page created. 
First call to use it will go out Monday 5 October 2020.
