### ISSUE TITLE
Use .md extension for txt files

### ISSUE THREAD

**Issue by jimt** [phase4ground/documents#17]
I suggest using Markdown for the text files in the documentation. At the simplest level, simply using a **.md** extension instead of **.txt** would allow GitHub to render things like the [Weekly Engineering Reports](https://github.com/phase4ground/documents/tree/master/Management/Weekly_Engineering_Reports) nicely when browsing the repository.  Plain text is a subset of markdown, provided paragraphs are separated by blank lines (which seems to be the case at least for the weekly reports.

**Comment by Abraxas3d** [comment]
You are exactly right and we need to simply get in there and get it done. I was relatively late to the .md party, but I'm now a true enthusiast. I think we can make some progress here this weekend. Thank you for the encouragement and explanation!
